# -*- coding: utf-8 -*-
"""Task 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aZVom_NaBMZ5uLn7vztipMA_XGMMqLLy
"""

#Problem 7

n = int(input())
integer_list = map(int, input().split())
t = tuple(integer_list)
print(abs(hash(t)))