# -*- coding: utf-8 -*-
"""Task 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aZVom_NaBMZ5uLn7vztipMA_XGMMqLLy
"""

#Problem 2

from itertools import groupby

def solve():
    s = input()
    result = []
    for k, g in groupby(s):
        result.append((len(list(g)), int(k)))
    print(*result)

solve()