# -*- coding: utf-8 -*-
"""Task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aZVom_NaBMZ5uLn7vztipMA_XGMMqLLy
"""

#Problem 1

if __name__ == '__main__':
    a = int(input())
    b = int(input())

#Adding
ADD = a + b
#Subtracting
SUB = a - b
#Product
PROD = a * b

print(ADD, SUB, PROD, sep="\n")