# -*- coding: utf-8 -*-
"""Task 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aZVom_NaBMZ5uLn7vztipMA_XGMMqLLy
"""

#Problem 8

if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    query_name = input()

    if query_name in student_marks:
        total_marks = sum(student_marks[query_name])
        average_marks = total_marks / len(student_marks[query_name])
        print(f"{average_marks:.2f}")
    else:
        print("Student not found")