# -*- coding: utf-8 -*-
"""Problem 6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G-bVkkwGGl3DtaFrvxwCX7KTYjULesk0
"""

from collections import Counter

# Read inputs
X = int(input())  # Number of shoes
shoe_sizes = list(map(int, input().split()))
shoe_inventory = Counter(shoe_sizes)

N = int(input())  # Number of customers

earnings = 0

for _ in range(N):
    size, price = map(int, input().split())
    if shoe_inventory[size] > 0:
        earnings += price
        shoe_inventory[size] -= 1  # Shoe sold

print(earnings)