# -*- coding: utf-8 -*-
"""Problem 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G-bVkkwGGl3DtaFrvxwCX7KTYjULesk0
"""

T = int(input())

for _ in range(T):
    try:
        a, b = input().split()
        result = int(a) // int(b)
        print(result)
    except (ValueError, ZeroDivisionError) as e:
        print("Error Code:", e)