# -*- coding: utf-8 -*-
"""Problem 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G-bVkkwGGl3DtaFrvxwCX7KTYjULesk0
"""

def average(array):
    # Use a set to remove duplicates
    distinct_heights = set(array)

    # Calculate the average
    return round(sum(distinct_heights) / len(distinct_heights), 3)

if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()))
    result = average(arr)
    print(result)