# -*- coding: utf-8 -*-
"""Problem 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G-bVkkwGGl3DtaFrvxwCX7KTYjULesk0
"""

import string

def print_rangoli(size):
    alpha = string.ascii_lowercase
    L = []

    for i in range(size):
        s = '-'.join(alpha[size-1:i:-1] + alpha[i:size])
        L.append(s.center(4*size - 3, '-'))

    print('\n'.join(L[::-1] + L[1:]))

if __name__ == '__main__':
    n = int(input())
    print_rangoli(n)