# -*- coding: utf-8 -*-
"""Problem 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G-bVkkwGGl3DtaFrvxwCX7KTYjULesk0
"""

import math
import os
import random
import re
import sys

def solve(s):
    result = ''
    capitalize_next = True

    for char in s:
        if capitalize_next and char.isalpha():
            result += char.upper()
            capitalize_next = False
        else:
            result += char
            if char == ' ':
                capitalize_next = True

    return result

if __name__ == '__main__':

    s = input("Enter a string: ")

    result = solve(s)

    with open('output.txt', 'w') as fptr:
        fptr.write(result + '\n')

    print(f"Result written to output.txt: {result}")