# -*- coding: utf-8 -*-
"""Problem 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G-bVkkwGGl3DtaFrvxwCX7KTYjULesk0
"""

import textwrap

def wrap(string, max_width):
    return '\n'.join(string[i:i+max_width] for i in range(0, len(string), max_width))

if __name__ == '__main__':
    string, max_width = input(), int(input())
    result = wrap(string, max_width)
    print(result)